env:
  es6: true
  jest: true

parserOptions:
  project: './tsconfig.json'

extends:
  - airbnb-typescript/base
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking

rules:
  '@typescript-eslint/no-unsafe-return': off
  '@typescript-eslint/no-unsafe-member-access': ['warn']
  '@typescript-eslint/no-unsafe-assignment': ['warn']
  '@typescript-eslint/no-unsafe-call': ['warn']
  '@typescript-eslint/indent': off
  '@typescript-eslint/no-for-in-array': 'off'
  '@typescript-eslint/no-unnecessary-qualifier': 'off'
  '@typescript-eslint/no-unnecessary-type-assertion': 'off'
  '@typescript-eslint/promise-function-async': 'off'
  '@typescript-eslint/restrict-plus-operands': 'off'
  '@typescript-eslint/naming-convention': 'off'
  
  no-console: ['warn', { allow: ['warn', 'error'] }]
  import/namespace: [2, { allowComputed: true }]
  import/prefer-default-export: 'off'

  prettier/prettier: ['error', { endOfLine: 'auto' }]

globals:
  FB: true
