openapi: 3.0.0
info:
  title: Exegesis Express Example API
  description: API for Exegesis Express Example
  version: 1.0.0
  contact:
    email: knyumatt@gmail.com
servers:
  - url: http://localhost:3000/v1
    description: localhost server
  - url: https://example.com/v1
    description: Production server - NOT EXIST
paths:
  /ping:
    x-exegesis-controller: ping
    get:
      tags:
        - Health Check
      operationId: ping
      summary: " - Health Check"
      description: |
        Health Check
      responses:
        "200":
          description: OK
  "/users/{id}":
    x-exegesis-controller: users
    get:
      tags:
        - Users - Resource
      operationId: getUser
      summary: " - Get user"
      description: |
        Get user by userId
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: unique Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: accessToken
