openapi: 3.0.0
info:
  title: Exegesis Express Example API
  description: API for Exegesis Express Example
  version: 1.0.0
  contact:
    email: knyumatt@gmail.com
tags:
  - name: Indexes
    description: Index management
servers:
  - url: /v1
paths:
  /ping:
    x-exegesis-controller: ping
    get:
      operationId: ping
      summary: " - Health Check"
      description: |
        Health Check
      responses:
        "200":
          description: OK
  "/users/{id}":
    x-exegesis-controller: users
    get:
      tags:
        - Users - Resource
      operationId: getUser
      summary: " - Get user"
      description: |
        Get user by userId
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: unique Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: accessToken
