---
openapi: 3.0.0
info:
  title: Exegesis Express Example API
  description: API for Exegesis Express Example
  version: 1.0.0
  contact:
    email: knyumatt@gmail.com
servers:
  - url: "http://localhost:3000/v1"
    description: "localhost server"
  - url: "https://example.com/v1"
    description: "Production server - NOT EXIST"
paths:
  /ping:
    $ref: "ping.yml#/paths/~1ping"
  /users/{id}:
    $ref: "users.yml#/paths/~1users~1{id}"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: accessToken