---
openapi: 3.0.0
info:
  title: Exegesis Express Example API
  description: API for Exegesis Express Example
  version: 1.0.0
  contact:
    email: knyumatt@gmail.com
tags:
  - name: Indexes
    description: Index management
servers:
  - url: "/v1"
paths:
  /ping:
    $ref: "ping.yml#/paths/~1ping"
  /users/{id}:
    $ref: "users.yml#/paths/~1users~1{id}"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: accessToken